# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: postgresql
  database: SmartDates-dev
  username: nrbessmer
  password: 
  host: localhost
  port: 5432
  #socket: /var/pgsql_socket/.s.PGSQL.5432
test:
  adapter: postgresql
  database: SmartDates-test
  username: nbessmer
  password:
  host: localhost
  port: 5432
  #socket: /var/pgsql_socket/.s.PGSQL.5432
prod:
  adapter: postgresql
  database: SmartDates-prod
  username: nbessmer
  password:
  host: localhost
  port: 5432
  #socket: /var/pgsql_socket/.s.PGSQL.5432
 

